'use client';

import { useState, useEffect } from 'react';
import { updateBrandSettings, getBrandSettings } from '@/actions/settings';
import { CldUploadWidget } from 'next-cloudinary';
import { Editor } from '@tinymce/tinymce-react';

export default function BrandSettingsPage() {
    const [settings, setSettings] = useState({
        companyName: 'QuickTrails',
        primaryLogoUrl: '',
        brandColors: { primary: '#1A202C', accent: '#D69E2E' },
        defaultInclusions: [] as string[],
        defaultExclusions: [] as string[],
        defaultTerms: '',
        defaultWelcomeMessage: '',
    });

    const [isSaving, setIsSaving] = useState(false);
    const [isLoading, setIsLoading] = useState(true);

    // State for the temporary inputs when adding a new item
    const [newInclusion, setNewInclusion] = useState('');
    const [newExclusion, setNewExclusion] = useState('');

    // FETCH DATA ON LOAD
    useEffect(() => {
        async function loadSettings() {
            const data = await getBrandSettings();
            if (data) {
                setSettings({
                    companyName: data.companyName || '',
                    primaryLogoUrl: data.primaryLogoUrl || '',
                    brandColors: data.brandColors || { primary: '#1A202C', accent: '#D69E2E' },
                    // Keep them as arrays now!
                    defaultInclusions: data.defaultInclusions || [],
                    defaultExclusions: data.defaultExclusions || [],
                    defaultTerms: data.defaultTerms || '',
                    defaultWelcomeMessage: data.defaultWelcomeMessage || '',
                });
            }
            setIsLoading(false);
        }
        loadSettings();
    }, []);

    const handleSave = async () => {
        setIsSaving(true);
        const dataToSave = { ...settings };
        const res = await updateBrandSettings(dataToSave);
        if (res.success) alert('Brand Settings Updated successfully!');
        setIsSaving(false);
    };

    // --- ARRAY MANIPULATION HELPERS ---
    const addInclusion = () => {
        if (!newInclusion.trim()) return;
        setSettings({ ...settings, defaultInclusions: [...settings.defaultInclusions, newInclusion.trim()] });
        setNewInclusion('');
    };
    const removeInclusion = (index: number) => {
        const updated = settings.defaultInclusions.filter((_, i) => i !== index);
        setSettings({ ...settings, defaultInclusions: updated });
    };

    const addExclusion = () => {
        if (!newExclusion.trim()) return;
        setSettings({ ...settings, defaultExclusions: [...settings.defaultExclusions, newExclusion.trim()] });
        setNewExclusion('');
    };
    const removeExclusion = (index: number) => {
        const updated = settings.defaultExclusions.filter((_, i) => i !== index);
        setSettings({ ...settings, defaultExclusions: updated });
    };

    if (isLoading) {
        return <div className="min-h-screen flex items-center justify-center bg-gray-50"><div className="animate-pulse text-gray-500 font-medium">Loading brand settings...</div></div>;
    }

    return (
        <div className="max-w-4xl mx-auto p-8 bg-white shadow-sm mt-10 rounded-sm border border-gray-100">
            <h1 className="text-2xl font-serif font-bold text-gray-900 mb-2">Global Brand Settings</h1>
            <p className="text-gray-500 mb-8">These defaults will be applied to all new itineraries generated by your team.</p>

            <div className="space-y-8">
                {/* Identity Section */}
                <section className="grid grid-cols-2 gap-8">
                    <div>
                        <label className="block text-sm font-medium text-gray-700">Company Name</label>
                        <input
                            type="text"
                            value={settings.companyName}
                            onChange={(e) => setSettings({ ...settings, companyName: e.target.value })}
                            className="mt-1 w-full p-2 border border-gray-300 rounded focus:ring-amber-500 outline-none"
                        />
                    </div>
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-2">Primary Logo</label>
                        <div className="flex items-center gap-4">
                            <CldUploadWidget
                                uploadPreset="quicktrails_preset"
                                onSuccess={(result: any) => setSettings({ ...settings, primaryLogoUrl: result.info.secure_url })}
                            >
                                {({ open }) => (
                                    <button onClick={() => open()} className="px-4 py-2 border border-gray-300 text-sm rounded hover:bg-gray-50 shrink-0">
                                        Upload Corporate Logo
                                    </button>
                                )}
                            </CldUploadWidget>
                            {settings.primaryLogoUrl && <img src={settings.primaryLogoUrl} className="h-10 object-contain bg-gray-50 p-1 rounded" alt="Brand Logo" />}
                        </div>
                    </div>
                </section>

                {/* VISUAL COLOR PICKERS */}
                <section className="grid grid-cols-2 gap-8 pt-8 border-t border-gray-100">
                    <div>
                        <label className="block text-sm font-medium text-gray-700">Primary Brand Color</label>
                        <div className="flex items-center gap-3 mt-2">
                            <input
                                type="color"
                                value={settings.brandColors.primary}
                                onChange={(e) => setSettings({ ...settings, brandColors: { ...settings.brandColors, primary: e.target.value } })}
                                className="h-10 w-12 p-1 border border-gray-200 rounded cursor-pointer"
                            />
                            <span className="text-sm text-gray-500 font-mono uppercase">{settings.brandColors.primary}</span>
                        </div>
                        <p className="text-xs text-gray-400 mt-1">Used for major headings.</p>
                    </div>
                    <div>
                        <label className="block text-sm font-medium text-gray-700">Accent Brand Color</label>
                        <div className="flex items-center gap-3 mt-2">
                            <input
                                type="color"
                                value={settings.brandColors.accent}
                                onChange={(e) => setSettings({ ...settings, brandColors: { ...settings.brandColors, accent: e.target.value } })}
                                className="h-10 w-12 p-1 border border-gray-200 rounded cursor-pointer"
                            />
                            <span className="text-sm text-gray-500 font-mono uppercase">{settings.brandColors.accent}</span>
                        </div>
                        <p className="text-xs text-gray-400 mt-1">Used for highlights and active buttons.</p>
                    </div>
                </section>

                {/* Defaults Section: Inclusions & Exclusions */}
                <section className="grid grid-cols-2 gap-8 pt-8 border-t border-gray-100">

                    {/* INCLUSIONS BLOCK */}
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-2">Default Inclusions</label>
                        <div className="space-y-2 mb-3 max-h-48 overflow-y-auto pr-2">
                            {settings.defaultInclusions.map((item, idx) => (
                                <div key={idx} className="flex justify-between items-center p-2 bg-green-50 text-green-800 text-sm rounded border border-green-100 group">
                                    <div className="flex items-center gap-2 flex-grow mr-2">
                                        <span className="text-green-600 font-bold shrink-0">✓</span>
                                        {/* INLINE EDITABLE INPUT */}
                                        <input
                                            type="text"
                                            value={item}
                                            onChange={(e) => {
                                                const newInclusions = [...settings.defaultInclusions];
                                                newInclusions[idx] = e.target.value;
                                                setSettings({ ...settings, defaultInclusions: newInclusions });
                                            }}
                                            className="bg-transparent border-none outline-none flex-grow text-sm focus:ring-1 focus:ring-green-400 rounded px-1"
                                        />
                                    </div>
                                    <button onClick={() => removeInclusion(idx)} className="text-green-600 hover:text-red-500 font-bold leading-none px-2 text-lg opacity-0 group-hover:opacity-100 transition-opacity">×</button>
                                </div>
                            ))}
                        </div>
                        <div className="flex items-center gap-2">
                            <input
                                type="text"
                                value={newInclusion}
                                onChange={(e) => setNewInclusion(e.target.value)}
                                onKeyDown={(e) => e.key === 'Enter' && addInclusion()}
                                placeholder="Add an inclusion..."
                                className="flex-grow p-2 text-sm border border-gray-300 rounded focus:ring-amber-500 outline-none"
                            />
                            <button onClick={addInclusion} className="px-3 py-2 bg-gray-100 text-gray-700 text-sm font-medium rounded hover:bg-gray-200 border border-gray-300">
                                Add
                            </button>
                        </div>
                    </div>

                    {/* EXCLUSIONS BLOCK */}
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-2">Default Exclusions</label>
                        <div className="space-y-2 mb-3 max-h-48 overflow-y-auto pr-2">
                            {settings.defaultExclusions.map((item, idx) => (
                                <div key={idx} className="flex justify-between items-center p-2 bg-red-50 text-red-800 text-sm rounded border border-red-100 group">
                                    <div className="flex items-center gap-2 flex-grow mr-2">
                                        <span className="text-red-600 font-bold shrink-0">✗</span>
                                        {/* INLINE EDITABLE INPUT */}
                                        <input
                                            type="text"
                                            value={item}
                                            onChange={(e) => {
                                                const newExclusions = [...settings.defaultExclusions];
                                                newExclusions[idx] = e.target.value;
                                                setSettings({ ...settings, defaultExclusions: newExclusions });
                                            }}
                                            className="bg-transparent border-none outline-none flex-grow text-sm focus:ring-1 focus:ring-red-400 rounded px-1"
                                        />
                                    </div>
                                    <button onClick={() => removeExclusion(idx)} className="text-red-600 hover:text-red-800 font-bold leading-none px-2 text-lg opacity-0 group-hover:opacity-100 transition-opacity">×</button>
                                </div>
                            ))}
                        </div>
                        <div className="flex items-center gap-2">
                            <input
                                type="text"
                                value={newExclusion}
                                onChange={(e) => setNewExclusion(e.target.value)}
                                onKeyDown={(e) => e.key === 'Enter' && addExclusion()}
                                placeholder="Add an exclusion..."
                                className="flex-grow p-2 text-sm border border-gray-300 rounded focus:ring-amber-500 outline-none"
                            />
                            <button onClick={addExclusion} className="px-3 py-2 bg-gray-100 text-gray-700 text-sm font-medium rounded hover:bg-gray-200 border border-gray-300">
                                Add
                            </button>
                        </div>
                    </div>

                </section>

                <section className='pt-8'>
                    <label className="block text-sm font-medium text-gray-700 mb-2">Terms & Conditions</label>
                    {/* A wrapper div to control the height of the editor */}
                    <div className="bg-white rounded-md mb-4">
                        <Editor
                            apiKey="2ynva9q28qhx9bv959e24zywnc0zngkixss4y09fxl5ke4of"
                            value={settings.defaultTerms || ''}
                            onEditorChange={(content) => setSettings({ ...settings, defaultTerms: content })}
                            init={{
                                height: 450,
                                menubar: false,
                                plugins: [
                                    'advlist', 'autolink', 'lists', 'link', 'image', 'charmap', 'preview',
                                    'anchor', 'searchreplace', 'visualblocks', 'code', 'fullscreen',
                                    'insertdatetime', 'media', 'table', 'code'
                                ],
                                toolbar: 'undo redo | blocks | ' +
                                    'bold italic forecolor | alignleft aligncenter ' +
                                    'alignright alignjustify | bullist numlist outdent indent | ' +
                                    'removeformat | help',
                                content_style: 'body { font-family:Helvetica,Arial,sans-serif; font-size:14px; color: #374151; }',
                                nonbreaking_wrap: false
                            }}
                        />
                    </div>
                </section>

                <div className="pt-6">
                    <button
                        onClick={handleSave}
                        disabled={isSaving}
                        className="px-6 py-3 bg-gray-900 text-white font-medium rounded shadow-sm hover:bg-gray-800 transition disabled:opacity-50"
                    >
                        {isSaving ? 'Updating Database...' : 'Save Global Settings'}
                    </button>
                </div>
            </div>
        </div>
    );
}